#!/usr/bin/env python3
"""
Merge, deduplicate, and categorize patents from FPO + Google Patents sources.
Usage:
  python3 compile_patents.py --fpo /tmp/fpo.json --gp /tmp/gp.csv --out /tmp/patents.md
  python3 compile_patents.py --fpo /tmp/fpo.json --out /tmp/patents.md   (FPO only)
"""
import argparse
import csv
import json
import re
from collections import Counter, defaultdict
from pathlib import Path

# ──────────────────────────────────────────
# Keyword → Category mapping
# ──────────────────────────────────────────
CATEGORY_RULES = [
    ("Slicing",             r"slic|slicing|knife|knives|blade|cutter unit|caliber"),
    ("Thermoforming",       r"thermoform|deep.draw|deep draw|forming station|deep-draw"),
    ("Tray Sealer",         r"tray seal|tray sealer|tray-seal"),
    ("Chamber Machine",     r"chamber|vacuum bag|bag seal|bulk goods.*bag"),
    ("Sealing",             r"\bseal(ing)?\b(?!.*tray)(?!.*chamber)"),
    ("Cutting",             r"\bcut(ting)?\s+station|complete.cut|punching device"),
    ("Automation/Robot",    r"robot|picker|gripper|pick.and.place|loading station"),
    ("Conveying",           r"convey|transport|transfer|lane divid|race track"),
    ("Smart/Digital",       r"process param|bus node|digital|smart|predictiv|recipe|machine learning|AI"),
    ("High-pressure",       r"high.pressure|HPP"),
    ("Sustainable",         r"paper material|cardboard|fiber.contain|reclosable"),
    ("Shrink",              r"shrink"),
    ("Auxiliary",           r"winder|nozzle|suction|mandrel|mounting plate|drive unit|valve"),
    ("Packaging",           r"reclosable package|liquid.*package|package.*design"),
]


def categorize(title: str) -> str:
    t = title.lower()
    for cat, pattern in CATEGORY_RULES:
        if re.search(pattern, t):
            return cat
    return "Other"


def extract_year(date_str: str) -> str:
    if date_str and len(date_str) >= 4:
        return date_str[:4]
    return "-"


def load_fpo(path: str) -> list[dict]:
    with open(path) as f:
        data = json.load(f)
    patents = []
    for entry in data:
        patents.append({
            "id": entry.get("id", ""),
            "title": entry.get("title", ""),
            "year": "-",
            "grant_date": "",
            "status": "Unknown",
            "source": "FPO",
        })
    return patents


def load_gp(path: str) -> list[dict]:
    patents = []
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            granted = bool(row.get("grant_date", "").strip())
            patents.append({
                "id": row.get("id", "").strip(),
                "title": row.get("title", "").strip(),
                "year": extract_year(row.get("priority_date", "") or row.get("filing_date", "")),
                "grant_date": row.get("grant_date", ""),
                "status": "Granted" if granted else "Application",
                "source": "Google Patents",
            })
    return patents


def merge(lists: list[list[dict]]) -> list[dict]:
    seen = set()
    result = []
    for lst in lists:
        for p in lst:
            key = p["id"].upper().replace(" ", "").replace("-", "").replace("_", "")
            if key and key not in seen:
                seen.add(key)
                # Infer status from ID if not set
                if p["status"] == "Unknown":
                    pid = p["id"].upper()
                    if re.match(r"^US\d{8}A\d$", pid) or re.match(r"^US\d{4}\d+A\d$", pid):
                        p["status"] = "Application"
                    elif re.match(r"^US\d{7,8}$", pid) or re.match(r"^\d{7,8}$", pid):
                        p["status"] = "Granted"
                    elif "B1" in pid or "B2" in pid:
                        p["status"] = "Granted"
                    elif "A1" in pid or "A2" in pid or "A3" in pid:
                        p["status"] = "Application"
                # Add category
                p["category"] = categorize(p["title"])
                result.append(p)
    return result


def write_markdown(patents: list[dict], out_path: str, company: str = ""):
    granted = sum(1 for p in patents if p["status"] == "Granted")
    applied = sum(1 for p in patents if p["status"] == "Application")
    cats = Counter(p["category"] for p in patents)
    years = Counter(p["year"] for p in patents if p["year"] != "-")

    company_label = f" — {company}" if company else ""
    lines = [
        f"# Patent Search Results{company_label}\n",
        f"> Generated by patent-search skill | Total: **{len(patents)}** patents",
        f"> ✅ Granted: {granted} | 📋 Application: {applied}\n",
        "---\n",
        "## Summary\n",
        "| Category | Count |",
        "|----------|-------|",
    ]
    for cat, cnt in sorted(cats.items(), key=lambda x: -x[1]):
        lines.append(f"| {cat} | {cnt} |")

    if years:
        lines += [
            "\n| Year Range | Count |",
            "|------------|-------|",
        ]
        # Group by decade
        decade_map = defaultdict(int)
        for yr, cnt in years.items():
            try:
                d = str(int(yr) // 10 * 10) + "s"
            except ValueError:
                d = "Unknown"
            decade_map[d] += cnt
        for decade, cnt in sorted(decade_map.items()):
            lines.append(f"| {decade} | {cnt} |")

    lines.append("\n---\n")

    # Per-category sections
    by_cat = defaultdict(list)
    for p in patents:
        by_cat[p["category"]].append(p)

    for cat in sorted(by_cat.keys()):
        entries = sorted(by_cat[cat], key=lambda x: x.get("year", "0"), reverse=True)
        lines.append(f"\n## {cat} ({len(entries)} patents)\n")
        lines.append("| Patent No | Year | Title | Status |")
        lines.append("|-----------|------|-------|--------|")
        for p in entries:
            status = "✅" if p["status"] == "Granted" else "📋" if p["status"] == "Application" else "❓"
            title = p["title"][:70] + "…" if len(p["title"]) > 70 else p["title"]
            lines.append(f"| `{p['id']}` | {p['year']} | {title} | {status} |")

    Path(out_path).write_text("\n".join(lines), encoding="utf-8")
    print(f"Markdown saved: {out_path}")

    # Write CSV companion
    csv_path = out_path.replace(".md", ".csv")
    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["Patent_No", "Title", "Category", "Status", "Year", "Source"])
        for p in sorted(patents, key=lambda x: (x["category"], x.get("year", "0"))):
            writer.writerow([p["id"], p["title"], p["category"], p["status"], p.get("year","-"), p.get("source","")])
    print(f"CSV saved:      {csv_path}")


def main():
    parser = argparse.ArgumentParser(description="Compile patent data from multiple sources")
    parser.add_argument("--fpo", help="FPO JSON file (from fpo_search.py)")
    parser.add_argument("--gp", help="Google Patents CSV file (from google_patents_csv.py)")
    parser.add_argument("--out", default="/tmp/patents.md", help="Output Markdown file")
    parser.add_argument("--company", default="", help="Company name for report title")
    args = parser.parse_args()

    sources = []
    if args.fpo:
        fpo_data = load_fpo(args.fpo)
        print(f"Loaded {len(fpo_data)} patents from FPO")
        sources.append(fpo_data)
    if args.gp:
        gp_data = load_gp(args.gp)
        print(f"Loaded {len(gp_data)} patents from Google Patents")
        sources.append(gp_data)

    if not sources:
        print("Error: provide at least one source (--fpo or --gp)")
        return 1

    patents = merge(sources)
    print(f"Merged: {len(patents)} unique patents")

    write_markdown(patents, args.out, args.company)
    return 0


if __name__ == "__main__":
    exit(main())
